#server:
#  port: 8081
#spring:
#  data:
#    neo4j:
#      - uri=bolt://localhost:7687
#      - username=neo4j
#      - password=soulmate
#  cloud:
#    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"